version: "2"

services:
  ragemp-server:
    image: ragemp
    container_name: ragemp-server
    ports:
      - 22005:22005
      - 22005:22005/udp
    volumes:
      - /ragemp:/ragemp
    restart: always
